kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
  - cp .env.farfarway.example .env
  - yarn
  - yarn test
- name: gitea_release
  image: plugins/gitea-release
  settings:
    prerelease: true
    api_key:
      from_secret: gitea_token
    base_url: https://git.jeudi.dev/jeudi/pagarme
    files:
      - ./*
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
  when:
    event: tag      