module.exports.getUserById = require('./getUserById')
module.exports.getAllUsers = require('./getAllUsers')
module.exports.newUser = require('./newUser')
module.exports.updateUser = require('./updateUser')
module.exports.deleteUser = require('./deleteUser')

module.exports.getCustomerById = require('./getCustomerById')
module.exports.getAllCustomers = require('./getAllCustomers')
module.exports.newCustomer = require('./newCustomer')
module.exports.updateCustomer = require('./updateCustomer')
module.exports.deleteCustomer = require('./deleteCustomer')
